[platformio]
default_envs = pro_micro_16mhz

[env:pro_micro_16mhz]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 115200
lib_deps =
  tockn/MPU6050_tockn
build_flags =
  -D DEBUG=1
